export interface ConverterTool {
  id: string;
  name: string;
  description: string;
  icon: string; // emoji
  category: 'data' | 'text' | 'image' | 'encoding' | 'developer' | 'color';
  type: 'text-to-text' | 'file-to-file' | 'file-to-text' | 'text-to-file' | 'special';
  gradient: string; // tailwind gradient classes
}

export const categoryLabels: Record<string, string> = {
  data: 'Data Format',
  text: 'Text & Document',
  image: 'Image',
  encoding: 'Encoding & Crypto',
  developer: 'Developer Tools',
  color: 'Color & Design',
};

export const tools: ConverterTool[] = [
  // Data Format
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON arrays to CSV format with headers.',
    icon: '📋',
    category: 'data',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data into structured JSON objects.',
    icon: '📊',
    category: 'data',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    description: 'Parse XML and convert to JSON format.',
    icon: '📄',
    category: 'data',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    description: 'Convert YAML configuration to JSON.',
    icon: '⚙️',
    category: 'data',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON to clean YAML format.',
    icon: '⚙️',
    category: 'data',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'tsv-to-csv',
    name: 'TSV to CSV',
    description: 'Convert tab-separated values to comma-separated.',
    icon: '📋',
    category: 'data',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
  },

  // Text & Document
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML markup.',
    icon: '✍️',
    category: 'text',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-emerald-500/20 to-teal-500/20',
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Strip HTML and convert to clean Markdown.',
    icon: '✍️',
    category: 'text',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-emerald-500/20 to-teal-500/20',
  },
  {
    id: 'html-to-text',
    name: 'HTML to Plain Text',
    description: 'Extract plain text from HTML content.',
    icon: '📝',
    category: 'text',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-emerald-500/20 to-teal-500/20',
  },
  {
    id: 'rtf-to-text',
    name: 'RTF to Text',
    description: 'Extract text from RTF documents.',
    icon: '📄',
    category: 'text',
    type: 'file-to-text',
    gradient: 'bg-gradient-to-br from-emerald-500/20 to-teal-500/20',
  },

  // Image
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between PNG, JPEG, WebP, BMP, and GIF.',
    icon: '🖼️',
    category: 'image',
    type: 'special',
    gradient: 'bg-gradient-to-br from-rose-500/20 to-pink-500/20',
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Encode images as Base64 data URIs.',
    icon: '🔗',
    category: 'image',
    type: 'file-to-text',
    gradient: 'bg-gradient-to-br from-rose-500/20 to-pink-500/20',
  },
  {
    id: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Decode Base64 data URIs back to image files.',
    icon: '🖼️',
    category: 'image',
    type: 'text-to-file',
    gradient: 'bg-gradient-to-br from-rose-500/20 to-pink-500/20',
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Rasterize SVG vector files to PNG images.',
    icon: '🎯',
    category: 'image',
    type: 'file-to-file',
    gradient: 'bg-gradient-to-br from-rose-500/20 to-pink-500/20',
  },

  // Encoding & Crypto
  {
    id: 'base64-encode',
    name: 'Base64 Encode',
    description: 'Encode text or data to Base64 format.',
    icon: '🔐',
    category: 'encoding',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decode',
    description: 'Decode Base64 back to readable text.',
    icon: '🔓',
    category: 'encoding',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'url-encode',
    name: 'URL Encode',
    description: 'Encode strings for safe use in URLs.',
    icon: '🌐',
    category: 'encoding',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'url-decode',
    name: 'URL Decode',
    description: 'Decode percent-encoded URL strings.',
    icon: '🌐',
    category: 'encoding',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'html-entity-encode',
    name: 'HTML Entity Encode',
    description: 'Encode special characters to HTML entities.',
    icon: '📝',
    category: 'encoding',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'html-entity-decode',
    name: 'HTML Entity Decode',
    description: 'Decode HTML entities back to characters.',
    icon: '📝',
    category: 'encoding',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes.',
    icon: '🔢',
    category: 'encoding',
    type: 'special',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
  },

  // Developer Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, and validate JSON data.',
    icon: '📐',
    category: 'developer',
    type: 'special',
    gradient: 'bg-gradient-to-br from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, UPPER, and more.',
    icon: '🔤',
    category: 'developer',
    type: 'special',
    gradient: 'bg-gradient-to-br from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'epoch-converter',
    name: 'Epoch Converter',
    description: 'Convert between Unix timestamps and human-readable dates.',
    icon: '🕐',
    category: 'developer',
    type: 'special',
    gradient: 'bg-gradient-to-br from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with real-time matching.',
    icon: '🔎',
    category: 'developer',
    type: 'special',
    gradient: 'bg-gradient-to-br from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens.',
    icon: '🎫',
    category: 'developer',
    type: 'text-to-text',
    gradient: 'bg-gradient-to-br from-cyan-500/20 to-blue-500/20',
  },

  // Color & Design
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and CMYK.',
    icon: '🎨',
    category: 'color',
    type: 'special',
    gradient: 'bg-gradient-to-br from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'color-palette-generator',
    name: 'Palette Generator',
    description: 'Generate harmonious color palettes from a base color.',
    icon: '🌈',
    category: 'color',
    type: 'special',
    gradient: 'bg-gradient-to-br from-pink-500/20 to-rose-500/20',
  },
];